const Catalogue =[
{
        id:1,
        image:"images/bar1.jpg",
        name:"Klar Cocktail Bar",
        category:"Bar",
        rating:"4,5",
        views:"1085",
        link: "https://www.google.com/"
},
{    id:2,
    image:"images/nightclub1.jpg",
    name:"Dekada Club",
    category:"Night Club",
    rating:"4,0",
    views:"5258",
},
{    id:3,
    image:"images/nightclub2.jpg",
    name:"New Orleans",
    category:"Night Club",
    rating:"4,8",
    views:"4251",
},
{    id:4,
    image:"images/nightclub3.jpg",
    name:"Xxone night club",
    category:"Night Club",
    rating:"4,7",
    views:"4158",
},
{
    id:5,
    image:"images/nightclub4.jpg",
    name:"Sofia",
    category:"Night Club",
    rating:"4,5",
    views:"3635",
},
{    id:6,
    image:"images/nightclub5.jpg",
    name:"The View",
    category:"Night Club",
    rating:"4,2",
    views:"2856",
},
{    id:7,
    image:"images/nightclub6.jpg",
    name:"Club Mirage",
    category:"Night Club",
    rating:"4,1",
    views:"2584",
},
{    id:8,
    image:"images/nightclub7.jpg",
    name:"Capitol Warsaw Club",
    category:"Night Club",
    rating:"3,8",
    views:"1509",
},
{    id:9,
    image:"images/nightclub8.jpg",
    name:"Sogo Club",
    category:"Night Club",
    rating:"3,0",
    views:"846",
},
{    id:10,
    image:"images/hotel1.jpg",
    name:"Novotel Warszawa Centrum",
    category:"Hotel",
    rating:"3,0",
    views:"846",
},
{    id:11,
    image:"images/hotel2.jpg",
    name:"NYX Hotel Warsaw",
    category:"Hotel",
    rating:"3,0",
    views:"846",
},
{    id:12,
    image:"images/hotel3.jpg",
    name:"Hotel Gromada",
    category:"Hotel",
    rating:"3,0",
    views:"846",
},
{    id:13,
    image:"images/hotel4.jpg",
    name:"Warsaw Marriott Hotel",
    category:"Hotel",
    rating:"3,0",
    views:"846",
},
{    id:14,
    image:"images/hotel5.jpg",
    name:"Radisson Collection Hotel, Warsaw",
    category:"Hotel",
    rating:"3,0",
    views:"846",
},
{    id:15,
    image:"images/hotel6.jpg",
    name:"B&B Hotel Warszawa-Okęcie",
    category:"Hotel",
    rating:"3,0",
    views:"846",
},
{    id:16,
    image:"images/hotel7.jpg",
    name:"ibis budget Warszawa Centrum",
    category:"Hotel",
    rating:"3,0",
    views:"846",
},
{    id:17,
    image:"images/hotel8.jpg",
    name:"Hotel Campanile Warszawa",
    category:"Hotel",
    rating:"3,0",
    views:"846",
},
{    id:18,
    image:"images/restaurant1.jpg",
    name:"Sushi Royal",
    category:"Restaurant",
    rating:"3,0",
    views:"846",
},
{    id:19,
    image:"images/restaurant2.jpg",
    name:"Restro",
    category:"Restaurant",
    rating:"3,0",
    views:"846",
},
{    id:20,
    image:"images/restaurant3.jpg",
    name:"Pianka",
    category:"Restaurant",
    rating:"3,0",
    views:"846",
},
{    id:21,
    image:"images/restaurant4.jpg",
    name:"Winestone Warszawa Centrum",
    category:"Restaurant",
    rating:"3,0",
    views:"846",
},
{    id:22,
    image:"images/restaurant5.jpg",
    name:"Restauracja Strefa",
    category:"Restaurant",
    rating:"3,0",
    views:"846",
},
{    id:23,
    image:"images/restaurant6.jpg",
    name:"Nasza Knajpka",
    category:"Restaurant",
    rating:"3,0",
    views:"846",
},
{    id:24,
    image:"images/restaurant7.jpg",
    name:"Restauracja Nasze Miejsce",
    category:"Restaurant",
    rating:"3,0",
    views:"846",
},
{    id:25,
    image:"images/restaurant8.jpg",
    name:"Restauracja polska HEKTOR",
    category:"Restaurant",
    rating:"3,0",
    views:"846",
},
{
    id:26,
    image:"images/bar2.jpg",
    name:"Irish Pub Miodowa",
    category:"Bar",
    rating:"4,5",
    views:"1085",
},
{
    id:27,
    image:"images/bar3.jpg",
    name:"Podwale Bar and Books",
    category:"Bar",
    rating:"4,5",
    views:"1085",
    },
{
       id:28,
        image:"images/bar4.jpg",
        name:"The Roots Cocktail Bar",
        category:"Bar",
        rating:"4,5",
        views:"1085",
        },
    {
            id:29,
            image:"images/bar5.jpg",
            name:"Głębokie Gardło SHOT BAR",
            category:"Bar",
            rating:"4,5",
            views:"1085",
},
{
    id:30,
    image:"images/bar6.jpg",
    name:"Pyza Warszawska",
    category:"Bar",
    rating:"4,5",
    views:"1085",
},
{
    id:31,
    image:"images/bar7.jpg",
    name:"Belgian Elephant Pub",
    category:"Bar",
    rating:"4,5",
    views:"1085",
},
{
    id:32,
    image:"images/bar8.jpg",
    name:"Bar Studio",
    category:"Bar",
    rating:"4,5",
    views:"1085",
}
];
export default Catalogue;